### ISSUE TITLE
Documentation for dest-branch

### ISSUE THREAD

**Issue by JMante1** [dsayling/branch-ops-action#7]
I want to use the functionality of pushing to a different branch than the branch I was on when the action was triggered. Could you provide an example using the dest-branch functionality?

**Comment by dsayling** [comment]
You should just be able to specify a branch name, if you want to randomize it, I suggest using the  `${{ github.event.pull_request.head.sha }}` value

```
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "New changes from ${{github.event.pull_request.head.ref}}"
        dest-branch: ${{github.event.pull_request.head.sha}}-new-checks
        verify-checks: true
        delete-after-checks: true
```
